apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoicmFwaGlrcmkiLCJwYXNzd29yZCI6ImdocF9yM0JhU2IwT0h0YndpclFrRFN0N3RZeGNrMGd2ZFYzUmtLblMiLCJhdXRoIjoiY21Gd2FHbHJjbWs2WjJod1gzSXpRbUZUWWpCUFNIUmlkMmx5VVd0RVUzUTNkRmw0WTJzd1ozWmtWak5TYTB0dVV3PT0ifX19
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
